version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Akalku12 
      - DATABASE_NAME=restokita
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=8293f8f38963e538e798b377de6d16005aef2734662c54a39159c33115c7628f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Akalku12
      - POSTGRES_DB=restokita
    volumes: 
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db: