name: Build and Deploy Code

#on:
#  push:
#    #branches: ["main", "anther branch"]
#    branches:
#      - "main"
#      - "another branch"
#  pull_request:
#    branches:
#      - "test_branch"
on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Akalku12 
      DATABASE_NAME: restokita
      DATABASE_USERNAME: postgres
      SECRET_KEY: 8293f8f38963e538e798b377de6d16005aef2734662c54a39159c33115c7628f
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Install python version 3.9
        uses:  actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all the dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: | 
          pip install pytest
          pytest

      